### ISSUE TITLE
[cli] build cmd to generate ts types for channels params

### ISSUE THREAD

**Issue by pmvald** [pinglue/pg-repo#2]
We want to build a new command  in @pinglue/cli called `build-channels-types` (adding to pg.ts and implementing in actions folder) as described below:

Background: The channel info is stores in the register.yaml files located at the folder `info`. For more info about info folder in packages refer to [this guide](https://github.com/pinglue/doc-pinglue/blob/main/src/040-fundamentals/050-info-folder.mdx). I added a complete registr.yaml for the `mongodb-pl` and you can use this package within the hello-world project to test your command. Note: other packages have wrong/incomplete register.yaml files - we will eed to update them as well.

Summary: The new command (build-channels-types) take the route name as its param (e.g., `pg build-channels-types route1`) and using the register.yaml for this route (if available) it generates typescript types for channels param, value and return values.

Details: when you run `pg build-channels-types route1` it creates a type file called `channels-types.ts` in the `src` folder and within the folder path same as its route. In out example, since the route is `route1` the file should be `src/route1/channels-types.ts`. Note that for root route (which is `./` and is equivalent to `pg build-channels-types .` or `pg build-channels-types` since param defaults to `./`) the file location will be `src/channels.types.ts`.

Within `channels-types.ts` define types for each channel described in registers.yaml as follows: assume the channel name is `channel-name` then the types will be: 

`ChannelNameParam` -> correspond the param
'ChannelNameValue' -> correspond to value
'ChannelNameReturn' -> correspond to return

Note that register.yaml define all these types are in [json schema format](https://json-schema.org/draft/2020-12/json-schema-core.html) - this is a very standard format and you can find a lot of resources on internet for it. 

naming rules: as showen above, the channel name is convrted to Pascal Case and suffixed with variable type (Params, Value, Return) to form the name of the type. One exception to this rule is the private channels. Private channels have names starting with "--" (you can see an example in @pgweb/login-pl package). For these provate channels the name should the Pascal case name prefixed with an underscore. So for example "--private-channel" channel name becomes `_PrivateChannelParams`, etc. 

So basically in this task you have to read the register.yaml json schemas and convert them to typescript types. PLEASE NOTE: there are tons of tools for working with json schemas, including converting them to typescript format (and many other formats). So just need to install such packages. One example could be [this](https://www.npmjs.com/package/json-schema-to-typescript). 

Notes:
* use *fs-extra* package for all file system operations
* use Node `path` package to create paths for files and folders. Do not use string concatenation. You can see lot of examples cross our codebase.
* do error handling (like show warning if package has to info for the route)
* to print on the output, use the print and style functions passed to action functions (see how other commands are implemented)
* error handling - write appropriate error message if a register.yaml file has the wrong format (or one of its json schema format is wrong)

**Comment by yuki-tylar** [comment]
When I run the command `pg build-channels-types`...

1. check all `registers.yaml` which is located in `packages/@pinglue/{folderName}/info/routes/` <==== **AM I CORRECT?**
In this case, `MongoDB-pl/info/routes/registers.yaml` will be found.

2. create type file. 
in this case,  `MongoDB-pl/src/channels.type.ts` will be created.

3. within the file, 3 types will be defined. in this case...
```
type GetMongodbCollectionParam = {
  name: string;
  exact?: boolean;
}
type GetMongodbCollectionValue  <========  WHAT IS THIS?
type GetMongodbCollectionReturn = {
  [k: string]: any // <-- because additionalProperties = true
}
```

**Comment by pmvald** [comment]
> When I run the command `pg build-channels-types`...
> 
> 1. check all `registers.yaml` which is located in `packages/@pinglue/{folderName}/info/routes/` <==== **AM I CORRECT?**

You run this cli from a package root. This is a tool used by package developers (including us!). So for example we run the command `npx pg build-channels-types route1` from the root of package `@pinglue/mongodb-pl`. In this case the program should look into the channels info for the route *route1* which is located at `@pinglue/mongodb-pl/info/routes/route1/registers.yaml`. Note that for the particular case of mongodb-pl *route1* should be the root route (i.e., route1=`.` or empty string and so the location will be `info/routes/registers.yaml`).  

Note that to run this command from a package root folder requires that `@pinglue/cli` is installed on that package. In fact we need to install `@pinglue/cli` as a *dev dependency*  on all of our packages. So if you want to test with `mongodb-pl` then you need to install `@pinglue/cli` as a dependency on it if it's not already done. (use `addto` script from the monorepo root as done in tutorials)


>    In this case, `MongoDB-pl/info/routes/registers.yaml` will be found.
> 2. create type file.
>    in this case,  `MongoDB-pl/src/channels.type.ts` will be created.
> 3. within the file, 3 types will be defined. in this case...
> 
> ```
> type GetMongodbCollectionParam = {
>   name: string;
>   exact?: boolean;  <==== Or do I define this exact field within the name field such as {name: {value: string, exact: boolean}}?
> }

yes that's fine. You basically leave this task to a package that converts json schema to ts, so whatever it produces. But yes in this case it should produce a type same as above. You just need to decide about the name. 

> type GetMongodbCollectionValue  <-- will not be defined because it's not defined in registers.yaml
yes if a type is not there we don't define it. Some channels don't have value or params and some do not return anything.

> type GetMongodbCollectionReturn = {
>   [k: string]: any // <-- because additionalProperties = true
> }
> ```

yes this is up to the package you are using for conversion, they should produce the right ts.
