### ISSUE TITLE
(cli): base cmds on a yaml file (part 1) - 50%

### ISSUE THREAD

**Issue by pmvald** [pinglue/pg-repo#27]
The focused package: @pinglue/cli

The file `pg.ts` is the main bin for the pg cli (which we used in the tutorials as well). This file is based on the well-known [commander tool](https://www.npmjs.com/package/commander).

As you can see. the file pg.ts is created manually. But we want to *generate* it from a yaml file which contains the info for the commands and args.

Steps:

* Create a yaml file that describes our CLI commands. I already added a starter yaml file (`cmds.yaml`) in the commit 2456fae381a85f4e929943de3dd65baa26ff409b . You can complete `cmds.yaml` based on `pg.ts`  

* Write your script at the designated file `scripts/build-pg-ts.js`. In short, your script has to read the `cmds.yaml` and generates code similar to `pg.ts` - for now keep the original `pg.ts` file and use the name `pg-gen.ts` for your generated file. We will compare these two files and once finalised we will change the name to pg.ts 

to generate the *action functions* import statements follow this rule: get the name of action from the yaml file which is always a came case name, (in my sample yaml the  first command's action name is `info` but it is erroneously written as infoAction, please modify) and the import statement should be `import <actionName>Action from "./actions/<action-name>.js"` - for example if the action name is `dumpReg` then the import should be `import dumpRegAction from "./actions/dump-reg.js"` - please note that some of the current pg.ts and also the action files might not follow this rule, we will need to rename them as well.

* make a commit, and I'll show you how to write some Jest tests for this

hints:

1. to read yaml file I use `yaml` package (see `pinglue` package for example)

2. this is a perfect example of using template tools like [handlebars](https://www.npmjs.com/package/handlebars). This will reduce your code to a few lines of  compiling the template. You can save your template at `src/pg.hb`. Don't forget that the package `handlebars` should be installed as a *dev dependency* (`--dev` flag)

3. we are working in monorepo settings. So first you need to setup a pg-repo monorepo (as explained in [the docs](https://github.com/pinglue/doc-pinglue/blob/main/src/020-get-started/010-monorepo-setup.mdx)). To install any package on a monorepo package do not use `npm install`, instead use `lerna add` or you can use the script `addto`. You can find several example of using `addto` script in tutorials (like hello-world).  

(FYI, later we will use this yaml file to generate a help page in our documentation site - so it has several benefits)

**Comment by aminsaedi** [comment]
My code is ready. But I have a problem to push it. After following instruction to setup the project and add a package using `lerna add prettier --dev` all `package-lock.json` files are modified.
I'm not sure that is it ok or I'm doing something wrong?

**Comment by pmvald** [comment]
when you use `lerna add some-package` it adds it to all the packages in the monorepo. If you want to add it to a particular package you have to use the switch `--scope=target-package` ([ref](https://github.com/lerna/lerna/tree/main/commands/add)). You can also use the script `addto` at the monorepo root (`npm run addto pretifier @pinglue/cli`) which does the same thing and uses `lerna add` under the hood.

**Comment by pmvald** [comment]
@aminsaedi Also add a basic test for this part as well
