### ISSUE TITLE
(cli): base cmds on a yaml file (part 2) - 50%

### ISSUE THREAD

**Issue by pmvald** [pinglue/pg-repo#29]
This is continuing issue #27 - so once we build the pg.ts file, we need to build the action files as well (within `./actions` folder). We already know the file name (but be careful the filename we save for the template is js file, we need to convert this name to be a ts file) - then for each action create a ts file within actions folder ONLY IF SUCH FILE DOES NOT EXIST (we don't want to overwrite the existing files for sure!)

The template for the new action file is:

```typescript
import {Registry} from "pinglue";

import type {
    CliActionSettings
} from "../cli-settings";

interface Options = {
    // I explain how to generate this options after the code
};

export default function(settings: CliActionSettings) {

    const {print, style} = settings;

    return async(
        route: string, options: Options
    ) => {
       // start here
   };
}
```
### Generating `Options` interface
In the template above the `Options` interface is built from the command's options. You can check some of teh exsiting code to understand better. But here is a summary:

flags: `-c, --channel <channel-name>` ==> field `channel: string` (regular option with mandatory value)
flags: `-c, --channel [channel-name]` ==> field `channel?: string` (regular option with optional value)
flags: `-c, --channel` ==> field `channel?: boolean` (regular flag option)

flags: '-n, --number <numbers...>' ==> field `number: string[]` (variadic option with mandatory value)
flags: '-l, --letter [letters...]' ==> field: `letter: string[] | boolean` (variadic option with optional value)

flags: `--no-import` ==> field `import: boolean`

Our source for above statements is [commander guide](https://www.npmjs.com/package/commander) - you can refer to this guide for more details or questions.

**Comment by aminsaedi** [comment]
I cheched docs of commander and also based on your explanation 

current cmd file is not matching with our actions files.

for example:
in cmd file for `channels-man` we have :`-k, --pkg <package-name>` , but in the `channels-man.ts`: `pkg?: string;`. So `pkg` should be mandatory but in the code it's note.
what should I do whith these confilicts?

**Comment by pmvald** [comment]
yeh the current action files might not follow the commands syntax. That's exactly why we need this dev-tool to help us sync our code with the definition. Later we will adjust the action files.

Also one thing I forgot to mention: the `Options` interface should be defined in a *separate file* called `action-filename-options.ts` (same folder actions). Then in the main action file we import Options from this file (instead of directly define the Options there). The rule for overwriting is as follows: 

* for the main action file: never overwrite
* for options-type file: always overwrite (this file is generated and should not contain any code otehr than the Options type definition)
