### ISSUE TITLE
feat(cli): generate settings type based on pg.yaml - 50%

### ISSUE THREAD

**Issue by pmvald** [pinglue/pg-repo#32]
A new pg command `build-settings-type`:

For each package generate `src/settings.ts` which export s the settings type of this package as defined by the json schema in the `settings` field of the packages's `pg.yaml` file. Similar to issue #2
  
Hint: 
* add your command to `pg.yaml` and use the `scripts/build-pg-ts` to build the pg.ts from the yaml file (do this before built-ts)
* your action file name should be build-settings-type.js

Also add the command `build-channels-types` you implemented in the previous task to the pg.yaml.

**Comment by yuki-tylar** [comment]
`add your command to pg.yaml and use the scripts/build-pg-ts to build the pg.ts from the yaml file (do this before built-ts)`

Is this part the one Amin is working?
So, I can skip this part, is that right?

**Comment by pmvald** [comment]
well I meant `cmds.yaml` not `pg.ts` ... Amin is done with the task and we merged the PR. So from now on to define a new command we just add them to the cmds.yaml and then define an action (in `actions` folder)

**Comment by yuki-tylar** [comment]
I added new command in `cmds.yaml` and run `npm run build-ts && npm run bt` from root.
I thought the command will build `pg.js` file but it seems `pg.js` file is not updated.

Am I doing something wrong?

**Comment by pmvald** [comment]
pg.ts is generated from cmds.yaml when you run the `scrips/build-pg-ts.js`. If you don't run this script then of course your pg.ts (and consequently pg.js) will not be updated. But to make it more automatic we can add this script to `build-ts` script of the cli package so that we don't have to run it separately (build-ts). You can make this change if you know how to do that.

FYI, there is no need to run `build-ts` from the root, it will build ts for ALL the packages. You just want to run it within your package. Also `bt` is not needed unless to install a new package on some of the monorepo packages. You should ;earn the meaning of each of these commands so that you can decide which command to run and when to run.
